### ISSUE TITLE
feature: add new filters

### ISSUE THREAD

**Issue by petqa** [flant/glaball#3]
hello, I'd like to have new filters for user search?

config.yaml:
```
hosts:
  team:
    project:
      gitlab-one:
        url: https://gitlab.one.net/
        token: s3cret
        rate_limit: false
      gitlab-second:
        url: https://gitlab.second.net/
        token: sup3R+s3cret
        rate_limit: false
```

I can't filter users now and users list shows only a project name.
```
glaball users list --active true --group_by=email
COUNT USER                                     HOSTS                                      CACHED
[2]   testuser@example.com                     [project project]                          [no]
[2]   testedser@example.com                    [project project]                          [no]
```

I would expect the following output:
```
glaball users list --active true --filter=count,user,name --group_by=email
COUNT USER                                     NAME
[2]   testuser@example.com                     [gitlab-one gitlab-second]
[2]   testedser@example.com                    [gitlab-one gitlab-second]
```
